version: '3.3'
services:
  postgres:
    container_name: muninn_postgres
    privileged: true
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - PGDATA=/tmp
    ports:
      - '5432:5432'
    image: 'postgres:12.2'
    restart: unless-stopped