version: '3.3'
services:
  muninn:
    container_name: muninn
    image: 'akarakoc@muninn:1.0.0'
    environment:
      - TWITTER_CONSUMER_KEY=
      - TWITTER_CONSUMER_SECRET=
      - TELEGRAM_TOKEN=
      - TELEGRAM_BOT_NAME=
      - MUNINN_RECHECK_PERIOD_IN_HOURS=6
      - DATA_SOURCE_URL=jdbc:postgresql://postgres:5432/muninn
      - DATA_SOURCE_USERNAME=postgres
      - DATA_SOURCE_PASSWORD=postgres
    volumes:
      - './muninn/log:/muninn/log'
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: muninn_postgres
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - './init-database.sh:/docker-entrypoint-initdb.d/init-database.sh'
      - './muninn/postgres-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    restart: unless-stopped
